
server:
    port: 8080
    
logging:
  level:
    root: WARN
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type]': TRACE
    '[org.hibernate.type.descriptor]': TRACE
    '[com.gbs.plus.springbootapp2]': DEBUG

spring:
    datasource:
        username: sa
        password: password
        url: jdbc:h2:mem:spring_boot
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
            path: /db
