
server:
    port: 8080
    

logging:
    pattern:
        file: '%n%msg%n'
    file: 
        name: relations.log
    level:
        root: WARN
        '[org.hibernate.SQL]': DEBUG
        # '[org.hibernate.type]': TRACE
        # '[org.hibernate.type.descriptor]': TRACE
        '[com.gbs.plus]': DEBUG

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mapping_demo
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
